apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: backenddb
  name: backenddb
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: backenddb
    spec:
      containers:
      - image: mongo
        name: backendmongo
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 27017
        resources: {}
      restartPolicy: Always
status: {}
