version: '2'
services: 
    webservice:
        image: quizwebapi
        build: .
        ports: 
            - 8080:5000
    backenddb:
        image: mongo
        ports:
            - 27017:27017
    cachingservice:
        image: redis
        ports: 
            - 6379:6379
    rabbitmq:
        image: "rabbitmq:3-management"
        hostname: "rmq"
        ports:
            - 15672:15672
            - 5672:5672
    elasticsearch:
        image: "elasticsearch:2"
        command: "elasticsearch -Des.cluster.name='graylog'"
        environment:
            - http.host=0.0.0.0
            - transport.host=localhost
            - network.host=0.0.0.0
            # Disable X-Pack security: https://www.elastic.co/guide/en/elasticsearch/reference/5.5/security-settings.html#general-security-settings
            - xpack.security.enabled=false
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        mem_limit: 1g
  # Graylog: https://hub.docker.com/r/graylog/graylog/
    graylog:
        image: graylog2/server:2.1.1-1
        environment:
            GRAYLOG_PASSWORD_SECRET: somepasswordpepper
            GRAYLOG_ROOT_PASSWORD_SHA2: 8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
            GRAYLOG_WEB_ENDPOINT_URI: http://localhost:9000/api
        links:
            - backenddb:mongo
            - elasticsearch:elasticsearch
        ports:
            # Graylog web interface and REST API
            - 9000:9000
            # Syslog TCP
            #- 514:514 # enable if needed
            # GELF TCP
            # - 12201:12201
            # GELF UDP
            # - 12201:12201/udp # Enable to log from host
        depends_on:
            - backenddb
            - elasticsearch