version: '2'
services: 
    webservice:
        image: quizwebapi
        build: .
        ports: 
            - "8080:5000"
    
    backenddb:
        image: mongo
        ports: 
            - "27017:27017"
    cachingservice:
        image: redis
        ports: 
            - "6379:6379"
    rabbitmq:
        image: "rabbitmq:3-management"
        hostname: "rmq"
        ports:
            - '15672:15672'
            - '5672:5672'