apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: elasticsearch
  name: elasticsearch
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: elasticsearch
    spec:
      containers:
      - args:
        - elasticsearch
        - -Des.cluster.name=graylog
        env:
        - name: ES_JAVA_OPTS
          value: -Xms512m -Xmx512m
        - name: http.host
          value: 0.0.0.0
        - name: network.host
          value: 0.0.0.0
        - name: transport.host
          value: localhost
        - name: xpack.security.enabled
          value: "false"
        image: elasticsearch:2
        name: elasticsearch
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        resources:
          limits:
            memory: "1073741824"
      restartPolicy: Always
status: {}
