apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: graylog
  name: graylog
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: graylog
    spec:
      containers:
      - env:
        - name: GRAYLOG_PASSWORD_SECRET
          value: somepasswordpepper
        - name: GRAYLOG_ROOT_PASSWORD_SHA2
          value: 8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
        - name: GRAYLOG_WEB_ENDPOINT_URI
          value: http://localhost:9000/api
        image: graylog2/server:2.1.1-1
        name: graylog
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9000
        resources: {}
      restartPolicy: Always
status: {}

