apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: webservice
  name: webservice
spec:
  type: NodePort
  ports:
  - name: "8080"
    port: 8080
    targetPort: 80
  selector:
    io.kompose.service: webservice
status:
  loadBalancer: {}
